changed outer to 0.06 in dual_panda-interface.l
ykawamura96/jsk_robot pull request #1
Opened 2021-06-09 01:50 UTC by softyanija

I changed "outer" in :send-gripper-grasp-action to grasp thicker objects.

2021-06-09 01:59 UTC, ykawamura96 commented
Thank you for PR!
Could you specify the purpose of this change, also, adding video clip or image also helps.

2021-06-09 02:22 UTC, softyanija commented
I wanted to grasp servo and fix to make KXR-repair demo, but couldn't. Arg width was 0 , inner and outer were both 0.005(m) so panda could have objects with a thickness of 5 mm or less. Then I changed outer to 0.06. As a result, panda can grasp servo and other parts of KXR. I'll send clip later.

2021-06-09 05:37 UTC, ykawamura96 requested changes
Please also make change in :start-grasp and :stop-grasp methods e.g. add arguments in the methods to change inner and outer parameters.

2021-06-09 05:37 UTC, ykawamura96 commented on jsk_panda_robot/panda_eus/euslisp/dual_panda-interface.l
> +   (act width speed force &key (wait t) (inner 0.005) (outer 0.06))
Please also make change in :[start-grasp](https://github.com/softyanija/jsk_robot/blob/2d139ea972114e4062184e98f66a40fcc0d619db/jsk_panda_robot/panda_eus/euslisp/dual_panda-interface.l#L159) and[ :stop-grasp](https://github.com/softyanija/jsk_robot/blob/2d139ea972114e4062184e98f66a40fcc0d619db/jsk_panda_robot/panda_eus/euslisp/dual_panda-interface.l#L166) methods e.g. add arguments in the methods to change inner and outer parameters,

2021-06-11 06:04 UTC, softyanija commented
I changed :start-grasp and :stop-grasp as the commit message says.

2021-06-11 22:57 UTC, merged

2021-06-14 02:26 UTC, softyanija commented
The former GIF is before improvement, the later is after improvement
![grasp_failure](https://user-images.githubusercontent.com/48650394/121831756-3dc74e80-cd03-11eb-9e64-8b65035f8a7f.gif)
![grasp_success](https://user-images.githubusercontent.com/48650394/121831760-4029a880-cd03-11eb-97ae-140c6d3ab855.gif)